### ISSUE TITLE
Error with Flutter 3.0

### ISSUE THREAD

**Issue by ghost** [shounakmulay/Telephony#141]
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/102141236/168348004-26a79834-3187-4902-8ec3-48574219e8cf.png">

I have just upgraded to flutter 3.0 and I am getting this error from this package. Any ideas how to solve this?

**Comment by MonsieurZbanowanYY** [comment]
same issue

**Comment by Jacques66** [comment]
Same here

### Addendum: temporary solution 
(kinda quick & dirty diy, because I need to advance in my project, so this is _at your own risk_ as I'm not an expert in either kotlin or the telephony plug-in).

I edited SmsMethodCallHandler.kt (complete path is in your error message), line 357 (for me).

Simply removed the question marks.

From:   `override fun onRequestPermissionsResult(requestCode: Int, permissions: Array<out String>?, grantResults: IntArray?): Boolean {
`
To:   `override fun onRequestPermissionsResult(requestCode: Int, permissions: Array<out String>, grantResults: IntArray): Boolean {
`

For me, it compiles and runs.  When this source file is refreshed (not often), this change needs to be applied again, but this is a small price, until a permanent solution appears.

**Comment by hatch01** [comment]
Jacques66's solution worked for me !

**Comment by shounakmulay** [comment]
Checkout https://pub.dev/packages/telephony/versions/0.2.0

**Comment by ghost** [comment]
Thanks @shounakmulay and @Jacques66
