### ISSUE TITLE
Mark selected received messages as read

### ISSUE THREAD

**Issue by ali80** [shounakmulay/Telephony#48]
Hi, thanks for the amazing work, 
Is there a way to mark some message in receive handler as read or even delete them?
Is there any delete message functionality currently available?

**Comment by shounakmulay** [comment]
No. You can't mark messages read or delete them. 
Android has some restrictions around such functionality. To be able to delete a SMS you're app needs to be the default sms app.

**Comment by cs145442** [comment]
Hey, this is regarding using the default handler,.

Do I need to explicitly request permissions in AndroidManifest.xml when the App is the default SMS App?

My App is being rejected, saying..
`Requested permissions do not match core functionality of the app
You declared Default SMS handler (and any other core functionality usage while default handler) as the core functionality of your app. However, after review, we found that your app does not match the declared use case(s). Learn more about permitted uses and exceptions.
Please either:
• Make changes to your app so that it meets the requirements of the declared core functionality or,
• Select a use case that matches your app’s functionality

This guy in the youtube [video](https://www.youtube.com/watch?v=xFLtuZP4TF0) suggests removing the default permissions when the app is the default handler.

- Removed the Permissions in AndroidManifest.xml (Only the 

Now, When I check for permissions (main.dart) and My app is already the default SMS handler (
. 
`Telephony telephony = Telephony.instance;
  bool permissionsGranted = await telephony.requestSmsPermissions ?? false;
  print("permissionsGranted: $permissionsGranted");`
  
  It results,
  `I/flutter (27544): permissionsGranted: true`
  
  However, When I try to getConversations as 
`getAllConversations() async {
    print("getAllConversations");
    smsConversationsList = await telephony.getConversations(
        sortOrder: [OrderBy(ConversationColumn.THREAD_ID, sort: Sort.ASC)]);
  }`

I get this. 
`I/flutter (27544): getAllConversations
I/flutter (27544): Error: PlatformException(failed_to_fetch_sms, Permission Denial: opening provider com.android.providers.telephony.SmsProvider from ProcessRecord{9d93ae0 27544:com.fiftygramx.ethosai/u0a303} (pid=27544, uid=10303) requires android.permission.READ_SMS or android.permission.WRITE_SMS, null, null)`


Please let me know if there's a workaround because my app has been rejected three times this week since the version integrating SMS conversations and in my app. Thanks in advance.
