### ISSUE TITLE
how the background -onBackgroundMessage infrom the foreground about new SMS?  

### ISSUE THREAD

**Issue by meridorkobi** [shounakmulay/Telephony#61]
The background part catch the SMS while the app in backround 
How can I infrom the app after moving to foreground about the message?   
if (result) {
      telephony.listenIncomingSms(
          onNewMessage: onMessage, onBackgroundMessage: onBackgroundMessage);
    }

**Comment by shounakmulay** [comment]
Because of the way dart and flutter works, the `background` part of the code is executed in a different isolate.
Isolates do not share memory and communication between different isolates is very primitive.

If you want to share something between foreground and background, the best way to do it in my opinion would be to have a common data source.

I will close this issue for now. Feel free to reopen if you have something to add.

Thanks.

**Comment by meridorkobi** [comment]
Thanks
what is a common data source? in mobile?
Kobi

**Comment by shounakmulay** [comment]
Any persistent store can act as a common data source.
Something like an sql database or shared preferences.

**Comment by meridorkobi** [comment]
thanks
Kobi
