### ISSUE TITLE
sms listener only receive the [personal inbox], but not the [notices inbox]

### ISSUE THREAD

**Issue by beiping96** [shounakmulay/Telephony#64]
Here is a problem happened on flymeOS.

The default SMS app has two inboxes, one is personal inbox, other is notices inbox.

 I had created my app and running it. When a SMS message from personal number will be joined into personal inbox, all works well.

 But, when other SMS messages, like auth code or advertisement, will be joined into notices inbox. My app can't find them. 

Any suggestions will be helpful. tks

**Comment by beiping96** [comment]
http://www.flymeos.com/

https://en.wikipedia.org/wiki/Meizu#Flyme

**Comment by shounakmulay** [comment]
Hey @beiping96 

Looks like this behaviour is due to the internal workings of flymeos. 

I don't know much about what restriction are present with flymeos and also don't have a device that runs on it to reproduce the issue.

I think searching about how to access all the messages on flymeos on native android would help you. If you do find a solution, you can fork and modify the native part of the telephony code to fit your use case.

Thanks.
